name: build
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'functions'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build typescript
        run: npm ci && npm run build
        working-directory: functions