name: build
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'functions/src'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          tsc